// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgkxkkluncfbngsmgwle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRna3hra2x1bmNmYm5nc21nd2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjM4NTMsImV4cCI6MjA2NDU5OTg1M30.VC90JIPsRkavjjOUg2I1Ku-cTyBtb_t8soHb6i9GfMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);